/**
 * One rubric, rendered as a styled HTML table.
 *
 * This is the single output format. It goes to either destination:
 *   - uploaded to Drive with a target mimeType of google-apps.document, which Drive converts
 *     into a native Google Doc;
 *   - or written to disk as a .html file, which opens in any browser and prints to PDF.
 *
 * It replaces the `docx` builder that used to serve the download path while Drive got a
 * plain-text flattening of the same rubric — the table structure was thrown away on the Drive
 * route entirely. One builder, two destinations, and the table survives both.
 *
 * ── Why the header row is flat ──
 *
 * The obvious layout, and the one the old .docx builder used, is a two-row header: "Criteria"
 * and "Points" spanning two rows, "Ratings" spanning the four level columns. It looks right in
 * Word and it breaks in Google Docs.
 *
 * The sibling Canvas Extractor Tools app shipped that exact layout and had to undo it. Its note
 * records why: Google Docs takes a table's column widths from the first row without expanding
 * spans, so a six-column table whose first row holds three cells leaves the last three columns
 * with no width at all. The fix is a flat header — one cell per real column — plus a <colgroup>
 * that states the widths explicitly.
 *
 * So do not reintroduce rowspan or colspan in the header here, however much tidier it reads.
 * The footer's colspan is fine: it is the last row, and with widths already fixed by the
 * <colgroup> nothing reads column sizes from it.
 */
import type { RubricData, RubricCriterion } from './geminiTypes'
import { parseRatingPoints } from './canvasUtils'

/**
 * What a criterion is worth, read the way Canvas reads it.
 *
 * The rubric object carries two point fields the AI wrote — `criterion.totalPoints` and
 * `rubric.totalPoints` — and this used to print both verbatim. They are claims about the rating
 * strings rather than derived from them, and the AI is not reliable about making them agree: one
 * observed rubric gave three criteria a hundred points each and then declared itself worth a
 * hundred, so the document a colleague would be handed said 100 while the rubric Canvas built was
 * worth 300.
 *
 * Nothing but the four rating strings reaches Canvas, so the document is built from those too,
 * through the very function that builds the Canvas payload. The two cannot now disagree.
 *
 * A rating whose points cannot be read falls back to the AI's own number — `buildRubricPayload`
 * refuses that CSV separately, and a blank cell here would say less than a wrong one.
 */
function criterionWorth(criterion: RubricCriterion): number {
  return parseRatingPoints(criterion.exemplary?.points) ?? criterion.totalPoints
}

/** The rubric's total: what its criteria are worth, added up. */
function rubricWorth(rubric: RubricData): number {
  return (rubric.criteria ?? []).reduce((sum, c) => sum + criterionWorth(c), 0)
}

const FONT = 'Arial, sans-serif'

const CELL = `border:1px solid #000;padding:6px;font-family:${FONT};font-size:11pt;`
const HEAD = `${CELL}background:#f3f4f6;font-weight:bold;text-align:center;`

// Criteria and Points are fixed; the four rating columns divide what is left. Points only ever
// holds something like "10 points", so it takes the smallest share.
const CRITERIA_WIDTH = 22
const POINTS_WIDTH = 10
const RATING_WIDTH = (100 - CRITERIA_WIDTH - POINTS_WIDTH) / 4

const RATING_LEVELS = ['Exemplary', 'Proficient', 'Developing', 'Unsatisfactory'] as const

/**
 * Escape text for HTML.
 *
 * Every value that reaches the table goes through here. Rubric text is generated by Gemini and
 * then edited by hand, so a stray `<`, `&` or quote is an ordinary occurrence rather than an
 * attack — but unescaped it would silently corrupt the table, and in the .html file it would be
 * live markup in a document the user opens in their browser.
 */
export function escapeHtml(value: string): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/** A rating cell: bold points on their own line, then the descriptor. */
function ratingCell(rating: { text: string; points: string } | undefined): string {
  if (!rating) return `<td style="${CELL}"></td>`
  const points = rating.points
    ? `<div style="text-align:center;font-weight:bold;margin-bottom:4px;">${escapeHtml(
        rating.points,
      )}</div>`
    : ''
  return `<td style="${CELL}vertical-align:top;">${points}${escapeHtml(rating.text)}</td>`
}

function criterionRow(criterion: RubricCriterion): string {
  const description = criterion.description
    ? `<div style="margin-top:4px;">${escapeHtml(criterion.description)}</div>`
    : ''
  const criteria =
    `<td style="${CELL}vertical-align:top;">` +
    `<strong>${escapeHtml(criterion.category)}</strong>${description}` +
    '</td>'

  const ratings = [
    criterion.exemplary,
    criterion.proficient,
    criterion.developing,
    criterion.unsatisfactory,
  ]
    .map(ratingCell)
    .join('')

  const points =
    `<td style="${CELL}text-align:center;vertical-align:middle;">` +
    `${escapeHtml(String(criterionWorth(criterion)))} points` +
    '</td>'

  return `<tr>${criteria}${ratings}${points}</tr>`
}

/** The table on its own, without a surrounding document. */
export function buildRubricTable(rubric: RubricData): string {
  const colgroup =
    '<colgroup>' +
    `<col style="width:${CRITERIA_WIDTH}%;">` +
    RATING_LEVELS.map(() => `<col style="width:${RATING_WIDTH}%;">`).join('') +
    `<col style="width:${POINTS_WIDTH}%;">` +
    '</colgroup>'

  // Flat header, one cell per real column. See the note at the top of this file.
  const header =
    '<tr>' +
    `<th style="${HEAD}">Criteria</th>` +
    RATING_LEVELS.map((level) => `<th style="${HEAD}">${level}</th>`).join('') +
    `<th style="${HEAD}">Points</th>` +
    '</tr>'

  const body = (rubric.criteria ?? []).map(criterionRow).join('')

  const footer =
    '<tr>' +
    `<td colspan="${RATING_LEVELS.length + 1}" style="${CELL}text-align:right;">` +
    '<strong>Total Points</strong></td>' +
    `<td style="${CELL}text-align:center;"><strong>${escapeHtml(
      String(rubricWorth(rubric)),
    )} points</strong></td>` +
    '</tr>'

  return `<table style="border-collapse:collapse;width:100%;">${colgroup}${header}${body}${footer}</table>`
}

/**
 * A complete HTML document around the table.
 *
 * `@page { size: landscape }` is for the local-save route: a six-column rubric printed portrait
 * squeezes the rating descriptions into a column of single words. Drive's importer ignores the
 * rule, so it costs nothing on the other route.
 */
export function buildRubricHtml(rubric: RubricData): string {
  return (
    '<!doctype html>' +
    '<html lang="en"><head><meta charset="utf-8">' +
    `<title>${escapeHtml(rubric.title)}</title>` +
    '<style>@page { size: landscape; margin: 0.5in; }' +
    `body { font-family: ${FONT}; margin: 24px; }</style>` +
    '</head><body>' +
    `<h1 style="font-family:${FONT};font-size:16pt;">${escapeHtml(rubric.title)}</h1>` +
    buildRubricTable(rubric) +
    '</body></html>'
  )
}

/**
 * Several rubrics in one document, each as its own titled table.
 *
 * One file rather than one per rubric, because an assignment's rubrics are reviewed together:
 * the whole thing goes to a faculty developer as a single attachment, and eight separate Docs
 * in a Drive folder is eight things to open and keep track of.
 *
 * Each rubric starts a new page when printed. A page break is a style Google Docs honours on
 * import, and without it the tables run into each other in a way that reads as one long rubric.
 */
export function buildRubricSetHtml(rubrics: RubricData[], documentTitle?: string): string {
  const title = documentTitle?.trim() || rubrics[0]?.title || 'Rubrics'
  /*
   * Each heading is a top-level <h1> carrying its own page break — never an <h1> inside a styled
   * <div>, which is what this used to be.
   *
   * Google Docs imported the first rubric's title as Heading 1 and every later one as ordinary
   * bold text, and the only difference between them was that the later ones sat inside
   * `<div style="page-break-before:always;">`. Docs flattens a styled block container and loses
   * the heading mapping of what is inside it. md2doc.py has always emitted headings at the top
   * level with inline styles and they import correctly, which is what identifies the wrapper
   * rather than the inline style as the cause.
   *
   * Real Heading 1s matter beyond appearance: they populate the Docs outline, so a document of
   * eight rubrics can be navigated from the sidebar instead of scrolled.
   */
  const sections = rubrics
    .map(
      (rubric, i) =>
        `<h1 style="${i > 0 ? 'page-break-before:always;' : ''}` +
        `font-family:${FONT};font-size:16pt;">${escapeHtml(rubric.title)}</h1>` +
        buildRubricTable(rubric),
    )
    .join('')

  return (
    '<!doctype html>' +
    '<html lang="en"><head><meta charset="utf-8">' +
    `<title>${escapeHtml(title)}</title>` +
    '<style>@page { size: landscape; margin: 0.5in; }' +
    `body { font-family: ${FONT}; margin: 24px; }</style>` +
    '</head><body>' +
    sections +
    '</body></html>'
  )
}

/** A filename stem safe on Windows and macOS, for the save dialog's default. */
export function rubricFileName(rubric: RubricData, extension: string): string {
  const stem =
    rubric.title
      .replace(/[<>:"/\\|?* -]/g, '')
      .replace(/\s+/g, '_')
      .replace(/^\.+/, '')
      .slice(0, 80)
      .trim() || 'Rubric'
  return `${stem}.${extension}`
}

/**
 * A document name carrying when it was written: "Essay Rubric (2026-09-25 6.25pm)".
 *
 * Goes on the Drive file name only, never inside the document. Two paths read a saved rubric back
 * — "Upload Replacement Rubric to App" and Part 2's document route — and both work from the
 * document's *text*, which never contains the file's name. A stamp in the heading would be one
 * more line sitting next to the title for the model to decide about; here there is nothing for it
 * to see.
 *
 * Year first because Drive sorts names as text: written 9/25 and 9/5 the versions interleave
 * wrongly, written 2026-09-25 and 2026-09-05 they do not.
 *
 * A full stop rather than a colon in the time, which is what a clock would use. Windows refuses
 * a colon in a filename, and a Google Doc's name becomes a filename the moment anyone downloads
 * it — as does this app's own "Save to this computer". One format that survives every
 * destination beats a prettier one that gets rewritten to "6_25pm" on the way out.
 */
export function timestampedName(base: string, when: Date = new Date()): string {
  const pad = (n: number) => String(n).padStart(2, '0')
  const hours = when.getHours()
  const suffix = hours < 12 ? 'am' : 'pm'
  const twelve = hours % 12 === 0 ? 12 : hours % 12

  const stamp =
    `${when.getFullYear()}-${pad(when.getMonth() + 1)}-${pad(when.getDate())} ` +
    `${twelve}.${pad(when.getMinutes())}${suffix}`

  const stem = (base ?? '').trim() || 'Rubric'
  return `${stem} (${stamp})`
}
